command: {max-tries: '&cTimed out trying to find a safe location to warp to.', finding: '&aFinding
    the perfect, safe random teleport location...', successfully: '&aYou have been
    teleported to the coordinates &e{blockX}, {blockY}, {blockZ}&a.', cooldown: '&cWait
    more {secondsLeft} seconds for execute the command again.', dimension-not-allowed: '&cYou
    cannot random teleport to that dimension!', biome-not-allowed: '&cYou cannot random
    teleport to that biome!'}
