
["Client settings"]
	#Enable/disable better end sky, set this to false if you are experiencing graphical issues with shaders.
	customSkyEnabled = true
	#Enable/disable biome fog density, set this to false if you don't want thick fog in certain biomes
	fogDensityEnabled = true

