JUNGLE_LOOT = true
SPAWN_CRAZED = false
CRAZED_CHANCE = 0.4
MAX_HEIGHT = 10
RANGE_PER_LEVEL = 10
BASE_RANGE = 40
PROTECT_ABOVE = false
DISTANCE_CALC = "CYLINDER"
SPAWN_POWDER = true
DECORATION = true
