
#Discord RichPresence Config File
[Rich-Presence]
	#First line of Rich Presence
	Client-Name = "by Antibang"
	#Do you want servers to send you a customized rich presence text?
	#Also toggles hardcoded custom icons and text of not fully integrated servers like mineplex
	Custom-Messages-From-Server = true
	#Placeholders:
	#%ip%  Server IP
	Server-Text = "Playing on %ip%"
	#Setting this to true disables name changing through GUI
	Disable-Name-changing = true
	#Do you want to use custom Hivemc integration (show what game you are playing)?
	Hivemc-Integration = false
	#Disables config GUI
	#Requires config file editing to enable again
	Disable-Config-GUI = true
	#Do you want to use custom Hypixel integration (show what game you are playing and such)?
	Hypixel-Integration = false
	#No placeholders supported, Text that shows when you are in the main menu
	Main-Menu = "Currently exploring or developing"
	#Placeholders:
	#%coords% (X:??? Y:??? Z:???)
	#%world% World name
	Singleplayer-Text = "Currently exploring or developing"
	#Custom client id, see https://github.com/ErdbeerbaerLP/DiscordRichPresence/wiki/Set-up-custom-Icons-(for-Modpacks) for more info
	#Default: 511106082366554122
	client-id = "1017866875167842365"
	#Do you want to print log of this mod to ingame chat?
	LogToChat = false

