
#Combat Configuration
[combat_configuration]
	#Enable area of effects also being applied to players. 
	#If you do not want area of effects being applied to other players, disable this feature. [true / false]
	enableAreaOfEffectOnOtherPlayers = false
	#Add entities that will never be targeted by aggressive Dungeons effects. 
	#To do so, enter their registry names.
	effectTargetBlacklist = ["guardvillagers:guard", "minecraft:bat", "minecraft:bee", "minecraft:chicken", "minecraft:cod", "minecraft:cow", "minecraft:dolphin", "minecraft:donkey", "minecraft:fox", "minecraft:horse", "minecraft:iron_golem", "minecraft:mooshroom", "minecraft:ocelot", "minecraft:panda", "minecraft:parrot", "minecraft:pig", "minecraft:polar_bear", "minecraft:pufferfish", "minecraft:rabbit", "minecraft:salmon", "minecraft:sheep", "minecraft:squid", "minecraft:strider", "minecraft:trader_llama", "minecraft:tropical_fish", "minecraft:turtle", "minecraft:villager", "minecraft:wandering_trader", "minecraft:wolf"]
	#Enable dual wielding. 
	#If you do not want dual wielding, disable this feature. [true / false]
	enableDualWielding = true
	#Enable two handed weapon. 
	#If you do not want two handed weapon, disable this feature. [true / false]
	enableTwoHandedWeapon = true

	#Souls Configuration
	[combat_configuration.souls_configuration]
		#Enables keeping of souls upon death, disabled by default. [true / false]
		enableKeepSoulsOnDeath = false

	#Artifact Configuration
	[combat_configuration.artifact_configuration]
		#Set the durability for artifacts. [0-1024, default: 64
		#Range: 0 ~ 1024
		artifactDurability = 64

	#Elite Mob Configuration
	[combat_configuration.elite_mob_configuration]
		#Enables elite mobs, enabled by default. [true / false]
		enableEliteMobs = true
		#Base chance of an elite mob spawning. [0.0 - 1.0] 
		#Calculation: chance * difficulty.getSpecialMultiplier() 
		#Base chance for vanilla armor spawning is 0.15. Default is 0.15
		#Range: 0.0 ~ 1.0
		eliteMobsBaseChance = 0.15

