
[Enchantato-EnchantmentTableUsage]
	#If you enable this, the 'DisabledEnchantments' will become 'AllowedEnchantments'
	InvertedMode = false
	DisabledEnchantments = ["fins:crabs_favor", "scythd:crop_reaper"]

