#modifies the size of the leaves
#Range: 1 ~ 20
leafSize = 11
#modifies how long it takes for the leaves to disappear
#Values over 2000 are not recommend
#Range: > 100
leafLifespan = 120
#modifies the amount of leaves that are spawning
#Values over 10000 are not recommend
#Range: > 0
leafSpawnRate = 8
#modifier the amount of leaves are spawning from conifer trees
#Values over 10000 are not recommend
#Range: > 0
coniferLeafSpawnRate = 1
#whether player placed blocks should also drop leaves
dropFromPlayerPlacedBlocks = true
#how much room below the leaves block is needed for the leaves to spawn
#Range: 1 ~ 20
minimumFreeSpaceBelow = 2
#disable wind effects
disableWind = false
#windless dimensions
windlessDimension = ["minecraft:the_end"]

