
[Koi]
	#Enable/disable koi spawns
	"Koi Spawns" = true
	#Spawn weight for koi
	"Koi Spawn Weight" = 5
	#Min group for koi
	"Koi Min Group" = 1
	#Max group for koi
	"Koi Max Group" = 2

[Lovebird]
	#Enable/disable lovebird spawns
	"Lovebird Spawns" = true
	#Spawn weight for lovebirds
	"Lovebird Spawn Weight" = 18
	#Min group for lovebirds
	"Lovebird Min Group" = 3
	#Max group for lovebirds
	"Lovebird Max Group" = 5
	#Hatch chance for each lovebird egg
	"Lovebird Hatch Chance" = 0.5
	#Max egg clutch size for lovebirds
	"Lovebird Clutch Size" = 4

[Dottyback]
	#Enable/disable dottyback spawns
	"Dottyback Spawns" = true
	#Spawn weight for dottybacks
	"Dottyback Spawn Weight" = 15
	#Min group for dottybacks
	"Dottyback Min Group" = 2
	#Max group for dottybacks
	"Dottyback Max Group" = 3

[Pike]
	#Enable/disable pike spawns
	"Pike Spawns" = true
	#Spawn weight for pikes
	"Pike Spawn Weight" = 8
	#Min group for pikes
	"Pike Min Group" = 1
	#Max group for pikes
	"Pike Max Group" = 1

[Guppy]
	#Enable/disable guppy spawns
	"Guppy Spawns" = true
	#Spawn weight for guppies
	"Guppy Spawn Weight" = 8
	#Min group for guppies
	"Guppy Min Group" = 3
	#Max group for guppies
	"Guppy Max Group" = 6

[Shrimp]
	#Enable/disable shrimp spawns
	"Shrimp Spawns" = true
	#Spawn weight for shrimp
	"Shrimp Spawn Weight" = 4
	#Min group for shrimp
	"Shrimp Min Group" = 2
	#Max group for shrimp
	"Shrimp Max Group" = 4

[Gourami]
	#Enable/disable gourami spawns
	"Gourami Spawns" = true
	#Spawn weight for gourami
	"Gourami Spawn Weight" = 3
	#Min group for gourami
	"Gourami Min Group" = 1
	#Max group for gourami
	"Gourami Max Group" = 1

[Arowana]
	#Enable/disable arowana spawns
	"Arowana Spawns" = true
	#Spawn weight for arowana
	"Arowana Spawn Weight" = 4
	#Min group for arowana
	"Arowana Min Group" = 1
	#Max group for arowana
	"Arowana Max Group" = 1

["Ghost Crab"]
	#Enable/disable ghost crab spawns
	"Ghost Crab Spawns" = true
	#Spawn weight for ghost crab
	"Ghost Crab Spawn Weight" = 8
	#Min group for ghost crab
	"Ghost Crab Min Group" = 2
	#Max group for ghost crab
	"Ghost Crab Max Group" = 5

[Lorikeet]
	#Enable/disable lorikeet spawns
	"Lorikeet Spawns" = true
	#Spawn weight for lorikeet
	"Lorikeet Spawn Weight" = 12
	#Min group for lorikeet
	"Lorikeet Min Group" = 2
	#Max group for lorikeet
	"Lorikeet Max Group" = 4
	#Hatch chance for each lorikeet egg
	"Lorikeet Hatch Chance" = 0.4
	#Max egg clutch size for lorikeets
	"Lorikeet Clutch Size" = 4

[Conure]
	#Enable/disable conure spawns
	"Conure Spawns" = true
	#Spawn weight for conure
	"Conure Spawn Weight" = 18
	#Min group for conure
	"Conure Min Group" = 3
	#Max group for conure
	"Conure Max Group" = 5
	#Hatch chance for each conure egg
	"Conure Hatch Chance" = 0.5
	#Max egg clutch size for conures
	"Conure Clutch Size" = 4

[Spoonbill]
	#Enable/disable spoonbill spawns
	"Spoonbill Spawns" = true
	#Spawn weight for spoonbill
	"Spoonbill Spawn Weight" = 12
	#Min group for spoonbill
	"Spoonbill Min Group" = 1
	#Max group for spoonbill
	"Spoonbill Max Group" = 2
	#Hatch chance for each spoonbill egg
	"Spoonbill Hatch Chance" = 0.5
	#Max egg clutch size for spoonbills
	"Spoonbill Clutch Size" = 5

[Dove]
	#Enable/disable dove spawns
	"Dove Spawns" = true
	#Spawn weight for dove
	"Dove Spawn Weight" = 12
	#Min group for dove
	"Dove Min Group" = 2
	#Max group for dove
	"Dove Max Group" = 4
	#Hatch chance for each dove egg
	"Dove Hatch Chance" = 0.8
	#Max egg clutch size for doves
	"Dove Clutch Size" = 2

["Mandarin Duck"]
	#Enable/disable mandarin duck spawns
	"Mandarin Duck Spawns" = true
	#Spawn weight for mandarin duck
	"Mandarin Duck Spawn Weight" = 18
	#Min group for mandarin duck
	"Mandarin Duck Min Group" = 2
	#Max group for mandarin duck
	"Mandarin Duck Max Group" = 3
	#Hatch chance for each mandarin duck egg
	"Mandarin Duck Hatch Chance" = 0.6
	#Max egg clutch size for mandarin ducks
	"Mandarin Duck Clutch Size" = 8

[Kakapo]
	#Enable/disable kakapo spawns
	"Kakapo Spawns" = true
	#Spawn weight for kakapo
	"Kakapo Spawn Weight" = 3
	#Min group for kakapo
	"Kakapo Min Group" = 1
	#Max group for kakapo
	"Kakapo Max Group" = 2
	#Hatch chance for each kakapo egg
	"Kakapo Hatch Chance" = 0.1
	#Max egg clutch size for kakapos
	"Kakapo Clutch Size" = 4

[Raven]
	#Enable/disable raven spawns
	"Raven Spawns" = true
	#Spawn weight for raven
	"Raven Spawn Weight" = 21
	#Min group for raven
	"Raven Min Group" = 1
	#Max group for raven
	"Raven Max Group" = 3
	#Hatch chance for each raven egg
	"Raven Hatch Chance" = 0.4
	#Max egg clutch size for ravens
	"Raven Clutch Size" = 7

[Fairywren]
	#Enable/disable fairywren spawns
	"Fairywren Spawns" = true
	#Spawn weight for fairywren
	"Fairywren Spawn Weight" = 22
	#Min group for fairywren
	"Fairywren Min Group" = 3
	#Max group for fairywren
	"Fairywren Max Group" = 6
	#Hatch chance for each fairywren egg
	"Fairywren Hatch Chance" = 0.4
	#Max egg clutch size for fairywrens
	"Fairywren Clutch Size" = 4

["Golden Eagle"]
	#Enable/disable golden eagle spawns
	"Golden Eagle Spawns" = true
	#Spawn weight for golden eagle
	"Golden Eagle Spawn Weight" = 4
	#Min group for golden eagle
	"Golden Eagle Min Group" = 1
	#Max group for golden eagle
	"Golden Eagle Max Group" = 3
	#Hatch chance for each golden eagle egg
	"Golden Eagle Hatch Chance" = 0.4
	#Max egg clutch size for golden eagles
	"Golden Eagle Clutch Size" = 3

[Gyrfalcon]
	#Enable/disable gyrfalcon spawns
	"Gyrfalcon Spawns" = true
	#Spawn weight for gyrfalcon
	"Gyrfalcon Spawn Weight" = 4
	#Min group for gyrfalcon
	"Gyrfalcon Min Group" = 1
	#Max group for gyrfalcon
	"Gyrfalcon Max Group" = 2
	#Hatch chance for each gyrfalcon egg
	"Gyrfalcon Hatch Chance" = 0.3
	#Max egg clutch size for gyrfalcons
	"Gyrfalcon Clutch Size" = 5

["Red Kite"]
	#Enable/disable red kite spawns
	"Red Kite Spawns" = true
	#Spawn weight for red kite
	"Red Kite Spawn Weight" = 4
	#Min group for red kite
	"Red Kite Min Group" = 1
	#Max group for red kite
	"Red Kite Max Group" = 2
	#Hatch chance for each red kite egg
	"Red Kite Hatch Chance" = 0.3
	#Max egg clutch size for red kites
	"Red Kite Clutch Size" = 4

["Steller's Sea Eagle"]
	#Enable/disable stellers sea eagle spawns
	"Stellers Sea Eagle Spawns" = true
	#Spawn weight for stellers sea eagle
	"Stellers Sea Eagle Spawn Weight" = 4
	#Min group for stellers sea eagle
	"Stellers Sea Eagle Min Group" = 1
	#Max group for stellers sea eagle
	"Stellers Sea Eagle Max Group" = 2
	#Hatch chance for each Steller's sea eagle egg
	"Steller's Sea Eagle Hatch Chance" = 0.2
	#Max egg clutch size for Steller's sea eagles
	"Steller's Sea Eagle Clutch Size" = 3

["Pygmy Falcon"]
	#Enable/disable pygmy falcon spawns
	"Pygmy Falcon Spawns" = true
	#Spawn weight for pygmy falcon
	"Pygmy Falcon Spawn Weight" = 5
	#Min group for pygmy falcon
	"Pygmy Falcon Min Group" = 1
	#Max group for pygmy falcon
	"Pygmy Falcon Max Group" = 2
	#Hatch chance for each pygmy falcon egg
	"Pygmy Falcon Hatch Chance" = 0.3
	#Max egg clutch size for pygmy falcons
	"Pygmy Falcon Clutch Size" = 4

["Barn Owl"]
	#Enable/disable barn owl spawns
	"Barn Owl Spawns" = true
	#Spawn weight for barn owl
	"Barn Owl Spawn Weight" = 10
	#Min group for barn owl
	"Barn Owl Min Group" = 1
	#Max group for barn owl
	"Barn Owl Max Group" = 2
	#Hatch chance for each barn owl egg
	"Barn Owl Hatch Chance" = 0.3
	#Max egg clutch size for barn owls
	"Barn Owl Clutch Size" = 7

[Goldfish]
	#Enable/disable goldfish spawns
	"Goldfish Spawns" = true
	#Spawn weight for goldfish
	"Goldfish Spawn Weight" = 3
	#Min group for goldfish
	"Goldfish Min Group" = 1
	#Max group for goldfish
	"Goldfish Max Group" = 3

[Ranchu]
	#Enable/disable ranchu spawns
	"Ranchu Spawns" = true
	#Spawn weight for ranchu
	"Ranchu Spawn Weight" = 2
	#Min group for ranchu
	"Ranchu Min Group" = 1
	#Max group for ranchu
	"Ranchu Max Group" = 2

["Wild Duck"]
	#Enable/disable wild duck spawns
	"Wild Duck Spawns" = true
	#Spawn weight for wild duck
	"Wild Duck Spawn Weight" = 18
	#Min group for wild duck
	"Wild Duck Min Group" = 1
	#Max group for wild duck
	"Wild Duck Max Group" = 2
	#Hatch chance for each wild duck egg
	"Wild Duck Hatch Chance" = 0.3
	#Max egg clutch size for wild ducks
	"Wild Duck Clutch Size" = 4

[Roller]
	#Enable/disable roller spawns
	"Roller Spawns" = true
	#Spawn weight for roller
	"Roller Spawn Weight" = 20
	#Min group for roller
	"Roller Min Group" = 1
	#Max group for roller
	"Roller Max Group" = 2
	#Hatch chance for each roller egg
	"Roller Hatch Chance" = 0.3
	#Max egg clutch size for rollers
	"Roller Clutch Size" = 4

[Chickadee]
	#Enable/disable chickadee spawns
	"Chickadee Spawns" = true
	#Spawn weight for chickadee
	"Chickadee Spawn Weight" = 21
	#Min group for chickadee
	"Chickadee Min Group" = 2
	#Max group for chickadee
	"Chickadee Max Group" = 3
	#Hatch chance for each chickadee egg
	"Chickadee Hatch Chance" = 0.3
	#Max egg clutch size for chickadees
	"Chickadee Clutch Size" = 6

["Pygmy Goose"]
	#Enable/disable pygmy goose spawns
	"Pygmy Goose Spawns" = true
	#Spawn weight for pygmy goose
	"Pygmy Goose Spawn Weight" = 23
	#Min group for pygmy goose
	"Pygmy Goose Min Group" = 1
	#Max group for pygmy goose
	"Pygmy Goose Max Group" = 2
	#Hatch chance for each pygmy goose egg
	"Pygmy Goose Hatch Chance" = 0.2
	#Max egg clutch size for pygmy geese
	"Pygmy Goose Clutch Size" = 8

[Swallow]
	#Enable/disable swallow spawns
	"Swallow Spawns" = true
	#Spawn weight for swallow
	"Swallow Spawn Weight" = 22
	#Min group for swallow
	"Swallow Min Group" = 3
	#Max group for swallow
	"Swallow Max Group" = 5
	#Hatch chance for each wild duck egg
	"Wild Duck Hatch Chance" = 0.6
	#Max egg clutch size for wild ducks
	"Wild Duck Clutch Size" = 3

["Fire Goby"]
	#Enable/disable fire goby spawns
	"Fire Goby Spawns" = true
	#Spawn weight for fire goby
	"Fire Goby Spawn Weight" = 16
	#Min group for fire goby
	"Fire Goby Min Group" = 1
	#Max group for fire goby
	"Fire Goby Max Group" = 1

["Blue Tang"]
	#Enable/disable blue tang spawns
	"Blue Tang Spawns" = true
	#Spawn weight for blue tang
	"Blue Tang Spawn Weight" = 9
	#Min group for blue tang
	"Blue Tang Min Group" = 1
	#Max group for blue tang
	"Blue Tang Max Group" = 1

["Flame Angelfish"]
	#Enable/disable flame angelfish spawns
	"Flame Angelfish Spawns" = true
	#Spawn weight for flame angelfish
	"Flame Angelfish Spawn Weight" = 17
	#Min group for flame angelfish
	"Flame Angelfish Min Group" = 1
	#Max group for flame angelfish
	"Flame Angelfish Max Group" = 1

[Trout]
	#Enable/disable trout spawns
	"Trout Spawns" = true
	#Spawn weight for trout
	"Trout Spawn Weight" = 8
	#Min group for trout
	"Trout Min Group" = 1
	#Max group for trout
	"Trout Max Group" = 1

["Fiddler Crab"]
	#Enable/disable fiddler crab spawns
	"Fiddler Crab Spawns" = true
	#Spawn weight for fiddler crab
	"Fiddler Crab Spawn Weight" = 12
	#Min group for fiddler crab
	"Fiddler Crab Min Group" = 2
	#Max group for fiddler crab
	"Fiddler Crab Max Group" = 4

[Ibis]
	#Enable/disable ibis spawns
	"Ibis Spawns" = true
	#Spawn weight for ibis
	"Ibis Spawn Weight" = 18
	#Min group for ibis
	"Ibis Min Group" = 2
	#Max group for ibis
	"Ibis Max Group" = 4
	#Hatch chance for each ibis egg
	"Ibis Hatch Chance" = 0.3
	#Max egg clutch size for ibises
	"Ibis Clutch Size" = 4

["Red Snapper"]
	#Enable/disable red snapper spawns
	"Red Snapper Spawns" = true
	#Spawn weight for red snapper
	"Red Snapper Spawn Weight" = 3
	#Min group for red snapper
	"Red Snapper Min Group" = 3
	#Max group for red snapper
	"Red Snapper Max Group" = 4

["Wood Duck"]
	#Enable/disable wood duck spawns
	"Wood Duck Spawns" = true
	#Spawn weight for wood duck
	"Wood Duck Spawn Weight" = 19
	#Min group for wood duck
	"Wood Duck Min Group" = 2
	#Max group for wood duck
	"Wood Duck Max Group" = 3
	#Hatch chance for each wood duck egg
	"Wild Duck Hatch Chance" = 0.3
	#Max egg clutch size for wood ducks
	"Wild Duck Clutch Size" = 8

[Peafowl]
	#Enable/disable peafowl spawns
	"Peafowl Spawns" = true
	#Spawn weight for peafowl
	"Peafowl Spawn Weight" = 15
	#Min group for peafowl
	"Peafowl Min Group" = 1
	#Max group for peafowl
	"Peafowl Max Group" = 2
	#Hatch chance for each peafowl egg
	"Peafowl Hatch Chance" = 0.3
	#Max egg clutch size for peafowls
	"Peafowl Clutch Size" = 6

[Sparrow]
	#Enable/disable sparrow spawns
	"Sparrow Spawns" = true
	#Spawn weight for sparrows
	"Sparrow Spawn Weight" = 24
	#Min group for sparrows
	"Sparrow Min Group" = 4
	#Max group for sparrows
	"Sparrow Max Group" = 7
	#Hatch chance for each sparrow egg
	"Sparrow Hatch Chance" = 0.6
	#Max egg clutch size for sparrow
	"Sparrow Clutch Size" = 5

[Bushtit]
	#Enable/disable bushtit spawns
	"Bushtit Spawns" = true
	#Spawn weight for bushtits
	"Bushtit Spawn Weight" = 18
	#Min group for bushtits
	"Bushtit Min Group" = 3
	#Max group for bushtits
	"Bushtit Max Group" = 5
	#Hatch chance for each bushtit egg
	"Bushtit Hatch Chance" = 0.4
	#Max egg clutch size for bushtits
	"Bushtit Clutch Size" = 6

[Laughingthrush]
	#Enable/disable laughingthrush spawns
	"Laughingthrush Spawns" = true
	#Spawn weight for laughingthrushes
	"Laughingthrush Spawn Weight" = 16
	#Min group for laughingthrushes
	"Laughingthrush Min Group" = 3
	#Max group for laughingthrushes
	"Laughingthrush Max Group" = 5
	#Hatch chance for each laughingthrush egg
	"Laughingthrush Hatch Chance" = 0.5
	#Max egg clutch size for laughingthrushes
	"Laughingthrush Clutch Size" = 4

["Eagle owl"]
	#Enable/disable eagleowl spawns
	"Eagle Owl Spawns" = true
	#Spawn weight for eagle owls
	"Eagle Owl Spawn Weight" = 10
	#Min group for eagle owls
	"Eagle Owl Min Group" = 1
	#Max group for eagle owls
	"Eagle Owl Max Group" = 2
	#Hatch chance for each eagle owl egg
	"Eagle Owl Hatch Chance" = 0.5
	#Max egg clutch size for eagle owls
	"Eagle Owl Clutch Size" = 2

[Robin]
	#Enable/disable robin spawns
	"Robin Spawns" = true
	#Spawn weight for robins
	"Robin Spawn Weight" = 18
	#Min group for robins
	"Robin Min Group" = 3
	#Max group for robins
	"Robin Max Group" = 4
	#Hatch chance for each robin egg
	"Robin Hatch Chance" = 0.4
	#Max egg clutch size for robins
	"Robin Clutch Size" = 6

[Magpie]
	#Enable/disable magpie spawns
	"Magpie Spawns" = true
	#Spawn weight for magpies
	"Magpie Spawn Weight" = 16
	#Min group for magpies
	"Magpie Min Group" = 3
	#Max group for magpies
	"Magpie Max Group" = 4
	#Hatch chance for each magpie egg
	"Magpie Hatch Chance" = 0.3
	#Max egg clutch size for magpies
	"Magpie Clutch Size" = 7

[Goose]
	#Enable/disable goose spawns
	"Goose Spawns" = true
	#Spawn weight for goose
	"Goose Spawn Weight" = 19
	#Min group for goose
	"Goose Min Group" = 3
	#Max group for goose
	"Goose Max Group" = 5
	#Hatch chance for each goose egg
	"Goose Hatch Chance" = 0.4
	#Max egg clutch size for geese
	"Goose Clutch Size" = 7

[Osprey]
	#Enable/disable osprey spawns
	"Osprey Spawns" = true
	#Spawn weight for ospreys
	"Osprey Spawn Weight" = 5
	#Min group for ospreys
	"Osprey Min Group" = 1
	#Max group for ospreys
	"Osprey Max Group" = 2
	#Hatch chance for each osprey egg
	"Osprey Hatch Chance" = 0.2
	#Max egg clutch size for ospreys
	"Osprey Clutch Size" = 4

[Kingfisher]
	#Enable/disable kingfisher spawns
	"Kingfisher Spawns" = true
	#Spawn weight for kingfishers
	"Kingfisher Spawn Weight" = 20
	#Min group for kingfisher
	"Kingfisher Min Group" = 3
	#Max group for kingfisher
	"Kingfisher Max Group" = 5
	#Hatch chance for each kingfisher egg
	"Kingfisher Hatch Chance" = 0.3
	#Max egg clutch size for kingfisher
	"Kingfisher Clutch Size" = 6

[Pelican]
	#Enable/disable pelican spawns
	"Pelican Spawns" = true
	#Spawn weight for pelicans
	"Pelican Spawn Weight" = 18
	#Min group for pelican
	"Pelican Min Group" = 3
	#Max group for pelican
	"Pelican Max Group" = 6
	#Hatch chance for each pelican egg
	"Pelican Hatch Chance" = 0.4
	#Max egg clutch size for pelicans
	"Pelican Clutch Size" = 3

[Lapwing]
	#Enable/disable lapwing spawns
	"Lapwing Spawns" = true
	#Spawn weight for lapwings
	"Lapwing Spawn Weight" = 18
	#Min group for lapwing
	"Lapwing Min Group" = 3
	#Max group for lapwing
	"Lapwing Max Group" = 6
	#Hatch chance for each lapwing egg
	"Lapwing Hatch Chance" = 0.3
	#Max egg clutch size for lapwing
	"Lapwing Clutch Size" = 4

[Skua]
	#Enable/disable skua spawns
	"Skua Spawns" = true
	#Spawn weight for skuas
	"Skua Spawn Weight" = 11
	#Min group for skua
	"Skua Min Group" = 1
	#Max group for skua
	"Skua Max Group" = 3
	#Hatch chance for each skua egg
	"Skua Hatch Chance" = 0.3
	#Max egg clutch size for skuas
	"Skua Clutch Size" = 2

[Gameplay]
	#Gameplay: Enable/disable breed-only variants
	"Breed-Only Variants" = true
	#Gameplay: Enable/disable biome-specific variants
	"Biome-Specific Variants" = true
	#Gameplay: Enable/disable tamed birds following the player
	Following = true
	#Gameplay: Enable/disable tamed birds teleporting to the player while following
	Teleportation = true
	#Gameplay: Distance at which a following bird will teleport to you (higher value = greater distance)
	"Teleporting distance" = 5.0
	#Gameplay: Enable/disable raptors attacking prey
	"Raptor Attacks" = true
	#Gameplay: Enable/disable raptors throwing targets into air
	"Raptors Throw" = true
	#Rarity of albino ravens (higher number = rarer)
	"Albino Raven Rarity" = 500
	#Rarity of mutation lovebirds from breeding
	"Lovebird Mutation Rarity" = 10
	#Rarity of mutation peafowls from breeding
	"Peafowl Mutation Rarity" = 10
	#Rarity of mutation lorikeets from breeding
	"Lorikeet Mutation Rarity" = 10
	#Base multiplier of height (note: it's recommended to not change this unless you want all entities to be larger/smaller
	"Height Base Multiplier" = 1.0
	#Standard deviation of height of entities (higher value = more variation, 0 = turning off basically)
	"Height Standard Deviation" = 0.14
	#Gameplay: Enable/disable height variation
	"Height Variation" = true
	#Gameplay: Enable/disable ducks dropping feathers
	"Ducks Drop Feathers" = true
	#Base time for egg to hatch, in ticks
	"Base Egg Hatch Time" = 6000

