#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft folder
[resourcepacks]
required = [
    "global_resource_packs/",
    "resourcepacks/BaerCraft.zip",
    "AntibangsRenditions-1.1.0.1",
    "xali's+Enhanced+Jungle+Wood+v1.2",
    "Better+Series",
    "diagonal-moon-e2920",
    "vixel-s-gilded-netherite-e2251",
    "Ore+Variants+v2.4",
    "Dragon+resource+pack",
    "Enhanced+Boss+Bars+1.0+[1.19]",
    "MBTR_v1.2",
    "DrownsToolTweaks",
    "Create+Style+Redstone+Pen+v2",
    "Spartan+Retextured",
    "updated_aquaculture-1.0",
    "Updated_Engineering_v1.4",
    "Dragon_Wild",
    "IAF-DE4THR4SH-Dragonsteel-Weaponry-v2.0+[1.16.X]",
    "FrostbiteBrimstone",
    "Supa+Lilies+1.16.4",
    "better-crops-3d-16x-with-tall-wheat",
    "better-vines-16x-e1550",
    "More_Nether_Fungi_(1.18)",
    "Spring_Flowers_(1.18)",
    "xali's+Potions+-+Free",
    "Better-Leaves-6.1-1.13+",
    "Jaden's+Nether+Expansion+v1.0.0",
    "Foliage+ V1.5.4.1",
    "DSWG+Glowing+Eyes+1.19+v1.1",
    "Fancy_Llama_Decor_(1.18)",
    "Xaero's+Minimap+-+Mod+Icons",
    "aBees-Reimagined§8-[v1]",
    "Chubby_Cheeksv4_No_Bunny",
    "Living_Dragon_(1.18)",
    "DragonRemastered[2][1.16.2-1.19.0]",
    "Nautilus3D_V1.51_[1.13++]",
    "Enchanted+Weapons+v2.1",
    "Enchanted+Tools+v2.5",
    "Enchanted+Armors,+v1.2",
    "WRTextureUpdate",
    "Wyrms+and+Pixels"
]

[datapacks]
required = [
    "global_data_packs/"
]

optional = [
    "optional_data_packs/",
    "global_packs/optional_datapacks/"
]