
[general]
	#Show empty armor icons?
	"Show empty icons" = true
	#Colors must be specified in #RRGGBB format
	"color values" = ["#FFFFFF", "#343061", "#C27193", "#EE988E", "#F5BB95", "#F5D6A2"]
	#Always show armor bar even if empty?
	"Always show bar" = false

