storagenetwork = false
tconstruct = false
fastfurnaceminusreplacement = true
sophisticatedbackpacks = false
fastfurnace = true
craftingstation = true
ironfurnaces = false
occultism = false
jei = true
extendedcrafting = false
fastbenchminusreplacement = true
refinedstorageaddons = false
craftingcraft = false
toms_storage = false
refinedstorage = false
prettypipes = false
fastsuite = true
fastbench = true
cyclic = false
appliedenergistics2 = true

