"Generate Deathmist" = true
"Generate Magma Golems under lava oceans" = true
"Generate Ash" = true
#Range: 0 ~ 256
"Spawnrate of Magmashrooms" = 3
#Range: 0 ~ 256
"Spawnrate of Violet Funguses" = 2
#Range: 0 ~ 256
"Spawnrate of Scarlet Funguses" = 3
#Range: 0 ~ 256
"Spawnrate of Endus Funguses" = 2
#Range: 0 ~ 256
"Spawnrate of Sparkshrooms" = 7
"Make Deathmist damage living entities" = true
"Spawn Soulbeasts" = true
#Range: 1 ~ 256
"Spawnrate of Soulbeasts" = 10
"Spawn Soul Paricles From Soulbeast" = true
"Spawn Ashlings" = true
#Range: 1 ~ 256
"Spawnrate of Ashling" = 25
"Spawn Leechounds" = true
"Give Leechound Regeneration" = true
#Range: 1 ~ 256
"Spawnrate of Leechounds" = 25
"Spawn Jawbers" = true
#Range: 1 ~ 256
"Spawnrate of Jawbers" = 60
"Spawn Weeping Strollers" = true
#Range: 1 ~ 256
"Spawnrate of Weeping Strollers" = 70
"Spawn Magma Golems under lava oceans" = true

