#
# Average distance between spawn attempts for Repurposed Structures Ruins.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
ruinsNetherMaxChunkDistance = 40
#Range: 1 ~ 1001
ruinsLandWarmMaxChunkDistance = 52
#Range: 1 ~ 1001
ruinsLandHotMaxChunkDistance = 48

