
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Villages 
# 1 for spawning in most chunks and 1001 for no spawn.
[Spawnrates]
	#Range: 1 ~ 1001
	badlandsVillageMaxChunkDistance = 42
	#Range: 1 ~ 1001
	birchVillageMaxChunkDistance = 52
	#Range: 1 ~ 1001
	darkForestVillageMaxChunkDistance = 52
	#Range: 1 ~ 1001
	jungleVillageMaxChunkDistance = 68
	#Range: 1 ~ 1001
	swampVillageMaxChunkDistance = 52
	#Range: 1 ~ 1001
	mountainsVillageMaxChunkDistance = 52
	#Range: 1 ~ 1001
	villageMushroomAverageChunkDistance = 24
	#Range: 1 ~ 1001
	giantTaigaVillageMaxChunkDistance = 54
	#Range: 1 ~ 1001
	oakVillageMaxChunkDistance = 52
	#Range: 1 ~ 1001
	crimsonVillageMaxChunkDistance = 30
	#Range: 1 ~ 1001
	warpedVillageMaxChunkDistance = 30

#-----------------------------------------------------------------------------------------
# Size of the village. This is how many pieces long a path can be from the start piece.
[Size]
	#Range: 1 ~ 30
	badlandsVillageSize = 25
	#Range: 1 ~ 30
	birchVillageSize = 20
	#Range: 1 ~ 30
	darkForestVillageSize = 21
	#Range: 1 ~ 30
	jungleVillageSize = 26
	#Range: 1 ~ 30
	swampVillageSize = 22
	#Range: 1 ~ 30
	mountainsVillageSize = 26
	#Range: 1 ~ 30
	mushroomVillageSize = 20
	#Range: 1 ~ 30
	giantTaigaVillageSize = 28
	#Range: 1 ~ 30
	oakVillageSize = 24
	#Range: 1 ~ 30
	crimsonVillageSize = 12
	#Range: 1 ~ 30
	warpedVillageSize = 12

